### ISSUE TITLE
can't compile on ubuntu 14.04

### ISSUE THREAD

**Issue by gijzelaerr** [radio-astro-debian/aoflagger-debian#2]
https://launchpadlibrarian.net/171787340/buildlog_ubuntu-trusty-amd64.aoflagger_2.5.0-1trusty_FAILEDTOBUILD.txt.gz

```
cd /build/buildd/aoflagger-2.5.0/obj-x86_64-linux-gnu/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/aoremoteclient.dir/link.txt --verbose=1
/usr/bin/x86_64-linux-gnu-g++    -Wall -DNDEBUG -funroll-loops -O3 -march=native -pedantic -Wno-long-long -Werror=vla    CMakeFiles/aoremoteclient.dir/aoremoteclient.cpp.o  -o aoremoteclient -rdynamic -lboost_thread -lboost_system -lboost_filesystem -lboost_date_time -lboost_signals -lfftw3 -lcasa_ms -lcasa_tables -lcasa_casa -lcasa_measures -llapack -lcfitsio libaoflagger.a libaoflaggerremote.a -lsigc-2.0 libaoflagger.a -lboost_thread -lboost_system -lboost_filesystem -lboost_date_time -lboost_signals -lfftw3 -lcasa_ms -lcasa_tables -lcasa_casa -lcasa_measures -llapack -lcfitsio -lpng -lz -lxml2 -Wl,-rpath,:::::::: 
/usr/bin/ld: libaoflaggerremote.a(client.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by gijzelaerr** [comment]
ok, we need to force the linking to pthread with gcc-4.8. I added this patch witch should fix the issue:

https://github.com/ska-sa/aoflagger-debian/blob/trusty/patches/pthread

**Comment by gijzelaerr** [comment]
build was successful on the launchpad buildfarm
